name: Update News Feeds

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual triggering
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/**'

jobs:
  update-feeds:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install chromium --with-deps

    - name: Create output directories
      run: |
        mkdir -p docs/feeds
        mkdir -p docs/status

    - name: Verify project structure
      run: |
        echo "Current directory:"
        pwd
        echo "Files in project:"
        ls -la
        echo "Files in src/:"
        ls -la src/
        echo "Package.json content:"
        cat package.json

    - name: Run news aggregation
      run: npm start
      env:
        NODE_ENV: production

    - name: Generate status report
      run: |
        echo "# Feed Update Status" > docs/status/latest.md
        echo "Last updated: $(date -u)" >> docs/status/latest.md
        echo "" >> docs/status/latest.md
        echo "## Feed Files Generated" >> docs/status/latest.md
        if [ -d "docs/feeds" ]; then
          for file in docs/feeds/*.xml; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              filesize=$(stat -c%s "$file" 2>/dev/null || stat -f%z "$file")
              echo "- $filename ($filesize bytes)" >> docs/status/latest.md
            fi
          done
        fi
        echo "" >> docs/status/latest.md
        echo "Generated by GitHub Actions" >> docs/status/latest.md

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🤖 Update news feeds - $(date -u +'%Y-%m-%d %H:%M:%S UTC')

          🔄 Automated news aggregation from multiple sources
          📰 Updated RSS feeds for all categories
          
          Generated by GitHub Actions
          "
          git push
        fi

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs

  deploy-pages:
    needs: update-feeds
    runs-on: ubuntu-latest
    
    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4